pipeline {
  tools {
    nodejs '8.11.0'
  }

  options {
    timeout(time: 2, unit: 'MINUTES')
  }

  stages {
    stage('Install dependencies') {
      sh 'npm i'
    }
    stage('Run tests') {
      sh 'npm t'
    }
  }
}
