pipeline {
  agent any
   options {
    timeout(time: 2, unit: 'MINUTES')
  }

  stages {
    stage('Build') {
      steps {
        sh "cd webapp && docker build -t elbuo8/webapp:${env.BUILD_NUMBER}"
      }
    }
    stage('Run tests') {
      steps {
        sh 'cd webapp && docker run -it elbuo8/webapp:${env.BUILD_NUMBER} npm t'
      }
    }
  }
}
